export const resources = {
    seeDetails: 'see details',
    eur: ' EUR',
    hasBeenAddedToCart: 'Added to the cart.',
    hasBeenRemovedFromCart: 'Removed from the cart.',
    addToCart: 'Add to Cart',
    removeFromCart: 'Remove from Cart',
    hasBeenAddedToFavorites: 'Added to the favorites.',
    hasBeenRemovedFromFavorites: 'Removed from the favorites.',
    price: 'Price:',
    priceAriaLabel: 'Price',
    eurSignal: '€',
    confirm: 'Confirm',
    sortBy: 'Sort by: ',
    contacts: 'CONTACTS',
    footer: `Bruno Carvalho © ${new Date().getFullYear()}`,
    github: 'https://github.com/BrunoFAC',
    linkedIn: 'https://www.linkedin.com/in/bruno-almeida07',
    store: 'STORE',
    alertNothingInCart: `There's nothing in your cart yet.`,
    alertNothingInFavorites: `There's nothing in your favorites yet.`,
    favorites: 'Favorites',
    cart: 'Cart',
    settings: 'Settings',
    home: 'Home',
    profile: 'Profile',
    incovinience: 'Sorry for the inconvenience.',
    underDevelopment: 'Functionality not available, under development.',
    reviews: 'Reviews',
    visit: 'Visit',
    buyNow: 'Buy now',
    buy: 'buy',
    purchased: 'Item purchased successfully.',
    summary: 'SUMMARY',
    totalOfItems: 'TOTAL OF ITEMS:',
    totalPrice: 'TOTAL PRICE:',
    products: 'PRODUCTS:',
    shortQuantity: 'Qty:',
    quantity: 'Quantity:',
    stockMax: 'Unable to order more of this product. The quantity ordered is not available.',
    singleProduct: 'Product',
    multiProducts: 'Products',
    cancel: 'cancel',
};
