export const resources = {
    manSection: `Men's Section`,
    womanSection: `Women's Section`,
    jewelerySection: 'Jewelery Section',
    electronicsSection: 'Electronics Section',
    seeDetails: 'see details',
    eur: ' EUR',
    hasBeenAddedToCart: 'Added to the cart.',
    hasBeenRemovedFromCart: 'Removed form cart.',
    hasBeenAddedAllFavoritesToCart: 'Added all favorites to the cart.',
    hasBeenRemovedAllFavoritesFromCart: 'Removed all favorites from the cart.',
    addToCart: 'Add to Cart',
    removeFromCart: 'Remove from Cart',
    hasBeenAddedToFavorites: 'Added to the favorites.',
    hasBeenRemovedFromFavorites: 'Removed from the favorites.',
    price: 'Price:',
    priceAriaLabel: 'Price',
    eurSignal: '€',
    confirm: 'Confirm',
    sortBy: 'Sort by: ',
    contacts: 'CONTACTS',
    footer: `Bruno Carvalho © ${new Date().getFullYear()}`,
    github: 'https://github.com/BrunoFAC',
    linkedIn: 'https://www.linkedin.com/in/bruno-almeida07',
    store: 'STORE',
    alertNothingInCart: `There's nothing in your cart yet.`,
    alertNothingInFavorites: `There's nothing in your favorites yet.`,
    favorites: 'Favorites',
    cart: 'Cart',
    home: 'Home',
    profile: 'Profile',
    incovinience: 'Sorry for the inconvenience.',
    underDevelopment: 'Functionality not available, under development.',
    reviews: 'Reviews',
    visit: 'Visit',
    buyNow: 'Buy now',
    buy: 'buy',
    singlePurchased: 'Item purchased successfully.',
    multiPurchased: 'Items purchased successfully.',
    summary: 'SUMMARY',
    totalOfItems: 'TOTAL OF ITEMS:',
    totalPrice: 'TOTAL PRICE:',
    products: 'PRODUCTS:',
    shortQuantity: 'Qty:',
    quantity: 'Quantity:',
    stockMax: 'Unable to order more of this product. The quantity ordered is not available.',
    singleProduct: 'Product',
    multiProducts: 'Products',
    cancel: 'cancel',
    fullName: 'Full Name',
    address: 'Address',
    zipCode: 'ZIP Code',
    nif: 'NIF',
    billingAddress: 'Billing Address',
    profileAddress: 'Profile Address',
    placeholder: {
        address: '1 Example Street, Block 2',
        fullName: 'Andrea Starford',
        nif: '123 456 789',
        zipCode: '0000-000',
    },
    errorBuyProducts: 'In order to buy these product(s), you need to fill every field correctly on the form.',
    successOrder: 'Order placed successfully! You will be redirected to the home page.',
    fullNameDisclaimer: 'Name field must have at least 3 characters.',
    addressDisclaimer: 'Address field must have at least 10 characters.',
    guest: 'Guest',
    disallowedImages: 'Error uploading the photo. Allowed types: PNG, JPEG, SVG',
    saveProfile: 'SAVE PROFILE',
    reset: 'RESET',
    saveProfileAlertError: 'You need to fill every field correctly.',
    saveProfileAlertInfo: 'No changes have been done.',
    saveProfileAlertSuccess: 'Profile saved successfully.',
    noOrders: `You haven't ordered anything yet...`,
    resetProfileAlertInfo: 'Profile is reseted.',
    resetProfileAlertSuccess: 'Reseted profile successfully.',
    orderHistory: 'Order History',
    oops: `Oops! It looks like we don't have any products here.`,
    hereToHelp: `Don't worry, we're here to help!`,
    checkOthers: `How about exploring the other categories? You will find great prices!`,
    reOrder: 'Re-order',
    invoice: 'INVOICE',
    date: 'Date',
};
